packages/ts-sdk/babel.config.json
packages/ts-sdk/package.json
packages/ts-sdk/pnpm-lock.yaml

This was introduced back when we were trying to get Jest working with various dependencies, but Ava doesn't rely on it. With JS transpiler ecosystem being such a mess, let's get off on the right foot by staying minimal as long as possible.

Remove stale dependency on Babel

---

packages/ts-sdk/package.json
packages/ts-sdk/pnpm-lock.yaml
packages/ts-sdk/src/test/typed_graph.test.ts
packages/ts-sdk/src/test/util.test.ts
packages/ts-sdk/src/types.ts
packages/ts-sdk/src/util.ts

Now, when we parse Docmapsy objects they will fail to validate if the date and url fields are malformed; they will additionally have the JS `Date` and `URL` objects to utilize conveniently.

Add datatype constraints for URL and Date types

---

packages/ts-sdk/src/test/util.test.ts
packages/ts-sdk/src/types.ts
packages/ts-sdk/src/util.ts

Various types rely on encoded Dates, however when they are encoded as DateFromISOString they will fail when decoding a structured object with a Date field or a timestamp number. This encoding allows either option as well as string.
- [-] I have updated the documentation to reflect any changes or additions to the project.
We may find that we wish to disallow use of a timestamp in these cases, however since these encoders always encode to string, i am not worried about it just yet.

[ts-sdk] Add date from unknown utility type

---

packages/ts-sdk/.eslintrc.cjs

Minor change to allow introduction of unused vars with underscore prefix names.
- [-] I have added or updated tests to cover any new functionality or bug fixes.
- [-] I have updated the documentation to reflect any changes or additions to the project.

sdk: allow unused vars with underscore prefix

---

packages/ts-sdk/src/test/types.test.ts
packages/ts-sdk/src/types.ts

The Docmap codec will now always return a value with @context key set. If the @context key is set to something other than the correct context, it will fail to decode (do we want this behavior?) If it is empty or null, it will be set to the correct key.
This should improve interoperability with JSON-LD.

add @context when missing

---

.github/workflows/release.yaml
README.md
babel.config.json
package.json
packages/ts-etl/package.json
packages/ts-sdk/README.md
packages/ts-sdk/package.json
packages/ts-sdk/tsconfig.json
pnpm-lock.yaml

This PR adds preconstruct as a workspace root dependency and integrates it into the release train.
This should enable the packages released from this monorepo to easily integrate into consumers regardless of whether those consumers use ESM, CJS, native TS, etc.
Resolves #57

WIP: use preconstruct for production building

---

packages/ts-etl/src/command.ts
packages/ts-etl/src/plugins/crossref/api.ts
packages/ts-etl/src/plugins/crossref/functions.ts
packages/ts-etl/test/unit/crossref/functions.test.ts
packages/ts-sdk/src/test/__fixtures__/from_root_examples.ts
packages/ts-sdk/src/test/typed_graph.test.ts
packages/ts-sdk/src/test/types.test.ts
packages/ts-sdk/src/types.ts

Changes names like `DocmapAssertion` to `Assertion`, `DocmapAction` to `Action`, etc.
This fix should improve useability as you can always import * as if you need to differentiate. This will be annoying to deprecate later, so let's go before 1.0 is released.

remove prefix strings from type names

---

packages/spa/src/utils.js
packages/ts-etl/src/command.ts
packages/ts-etl/src/plugins/crossref/api.ts
packages/ts-etl/test/integration/crossref.test.ts

Expose the configuration for the crossref client that the ETL uses to alert crossref API to who is using it. Allows access to better pools.
https://api.crossref.org/swagger-ui/index.html#Etiquette

Allow polite mailto specification in ETL

---

packages/ts-etl/src/plugins/crossref/api.ts
packages/ts-etl/test/integration/crossref.test.ts

When the crossref ETL plugin is processing its visitedIDs, it previously lowercased all IDs when checking for presence because DOIs are case-insensitive. However they were noot lowercased when inserting to the set, meaning any DOI with a capital letter is never considered "visited". This no longer occurs.
Case sensitivity is responsible for at least some of the error cases once believed attributable to #84 's use case.

fix case sensitivity bug

---

packages/ts-etl/README.md
packages/ts-etl/package.json
packages/ts-etl/src/cli.ts
pnpm-lock.yaml

Uses TSX as buildloader for running the packaged `bin` script `docmaps-etl`.
Doesn't exactly resolve #57 , but removes one major impetus for solving that quickly. Before this PR, it was not feasible to run `npm install @docmaps/etl && npx docmaps-etl item ...` because the compiled JS was not loadable by Node and there were ES module dependencies that got in the way of fixing this. We had to rely on `ts-node`.
Now we run `npx tsx` directly in the `cli.js` script and so the above invocation, as well as the faster invocation `pnpm docmaps-etl ...`, will work.

Use tsx for etl cli

---

package.json
pnpm-lock.yaml
scripts/jsonld-to-rdf.js

The jsonld-to-rdf script previously was unable to handle jsonld files with multiple top-level objects, like a jsonlines file. This change now supports that format of file.
No issues mention this specifically but it was made to support dataset generation while exploring for #93 

script improvement: handle multiline jsonld[lines] files

---

packages/ts-sdk/src/typed_graph.ts

Promulgate rather tahn throw errors in jsonld decode.

fix(ts-sdk): error handling if jsonld decode fails

---

.github/workflows/example-tests.yaml
.github/workflows/gh-pages.yaml
.github/workflows/release.yaml
.github/workflows/spa-tests.yaml
.github/workflows/specification-tests.yaml
.github/workflows/ts-etl-tests.yaml
.github/workflows/ts-sdk-tests.yaml
packages/ts-sdk/CONTRIBUTING.md
pnpm-lock.yaml

Updates lockfile and GHA automation to use pnpm 8
To match https://github.com/Docmaps-Project/ts-api-server/issues/16 , so all workstations are OK

update pnpm to 8

---

packages/http-client/.eslintrc.cjs
packages/http-client/.prettierrc.cjs
packages/http-client/README.md
packages/http-client/package.json
packages/http-client/src/client.ts
packages/http-client/src/contract.ts
packages/http-client/src/index.ts
packages/http-client/src/types.ts
packages/http-client/tsconfig.json
pnpm-lock.yaml
pnpm-workspace.yaml

The http-client package previously lived in https://github.com/Docmaps-Project/ts-api-server/, but that repo is going to be deprecated.
This PR adds it to the monorepo.
- https://github.com/Docmaps-Project/docmaps/issues/126
Note: there aren't any tests for this module. The tests all live within the ts-api-server `runtime` package. Once we add the runtime package, this code will be tested again.

http-client: move over http-client package

---

packages/widget/package.json
packages/widget/src/docmaps-widget.ts
packages/widget/src/styles.ts
packages/widget/test/integration/docmaps-widget.test.ts
pnpm-lock.yaml

Previously the nodes were displayed as a typical d3 force-layout graph.
Now they're displayed as a proper tree
List any issues that are related to this pull request, such as bug reports or feature requests.
There is a slight easing that happens after the graph is first rendered.

widget: Display nodes as a tree

---

packages/widget/index.html
packages/widget/src/docmaps-widget.ts
packages/widget/test/integration/docmaps-widget.test.ts

Nodes without types need to be styled differently since they have no label:
List any issues that are related to this pull request, such as bug reports or feature requests.

widget: Add outline to nodes with no type

---

packages/http-client/src/contract.ts
packages/http-client/src/index.ts
packages/http-client/src/types.ts
packages/http-server/package.json
packages/http-server/src/adapter/sparql_adapter.ts
packages/http-server/src/httpserver/command.ts
packages/http-server/src/httpserver/server.ts
packages/http-server/test/integration/httpserver.test.ts
packages/http-server/test/integration/utils.ts
packages/http-server/test/unit/sparql.test.ts
packages/http-server/test/utils.ts
pnpm-lock.yaml

Integrate Pino as a logging solution with convenient injection pathways so that diagnostic log lines can be emitted.
Emits log lines at the highly verbose `trace` level in the SPARQL adapter to improve diagnostics in our staging environment.
Adds a body structure to 404 errors.
Resolves #149 
Will rely on #115 to be particularly valuable

Enable logging in http-server

---

.github/workflows/widget-tests.yaml

Following some tip threads, I am trying to speed up tests for the widget by
using a pre-built container that has the matching browsers installed 
for widget test run.
Since docker images can be cached by github actions, this should speed things
up nicely.

Use pre-installed playwritght container for widget-tests

---

packages/widget/src/assets/detail-navigation-header.ts
packages/widget/src/docmaps-widget.ts
packages/widget/test/integration/docmaps-widget.test.ts

This pull request makes it so you can click the forward and back buttons in the timeline, and so you can click on a node in the timeline to go there.
#133 
N/A

feat(widget): The buttons in the timeline work

---

packages/widget/src/detail-view.ts
packages/widget/src/styles.ts
packages/widget/test/integration/docmaps-widget.test.ts

You can click links now.
The values in the `url` and `content` metadata fields are assumed to be links.
and on hover it looks like this:
This finishes #169
None

feat(widget): Make links clickable

---

packages/widget/src/detail-view.ts
packages/widget/test/integration/docmaps-widget.test.ts

[This commit](https://github.com/Docmaps-Project/docmaps/commit/14d63633c39ee701f1d9ce3a693b06ef7cfd3a4a) broke the formatting of metadata values that were lists.
This PR fixes that.
List any issues that are related to this pull request, such as bug reports or feature requests.

fix(widget): metadata fields with lists as values are displayed properly 

---

packages/widget/src/detail-navigation-header.ts
packages/widget/src/detail-view.ts
packages/widget/src/docmap-controller.ts
packages/widget/src/graph-view.ts
packages/widget/src/util.ts

- Extracts a `normalizeDisplayObject()` method that removes undefined values and puts the keys in the desired order. It is used right before nodes are displayed and right before they are merged, so we don't have to worry about accidentally dirtying a DisplayObject in some intermediate operation.
- Extracts a `mergeDisplayObjects(a, b)` so we don't have to remember to normalize the DisplayObjects every time we merge.
- Improve typing of `detail-view.ts` so we don't rely so heavily on `any`
- Moves utilities that were in `util.ts` but only relevant to the graph view or detail view into the files where they really belong.
- Renames some types and constants, and adds some comments documenting types or constants whose purpose might be unclear.
- Renames some methods
List any issues that are …

Widget: final round of refactors

---

packages/widget/src/docmap-controller.ts
packages/widget/test/unit/docmap-controller.test.ts

Include the validation error from the SDK in console output from widget when parsing fails
For diagnostics in #211 
Possibly we will want to wrap this behavior behind a `debug: true` flag for embedders in the future

Widget should display the full error message on the sPa

---

packages/widget/index.html
packages/widget/src/styles.ts

When some people view the details screen in the widget, there's a strange UI bug where the content is too big for the space it occupies.
I can't reproduce this bug myself, but this PR makes some tweaks to those styles hoping to fix it.
N/A

fix(widget): Try to fix the metadata UI bug

---

packages/spa/public/index.html
packages/spa/src/App.svelte
packages/widget/index.html
packages/widget/src/styles.ts

The docmap explorer wasn't working in Firefox and Safari because a CORS error that only happens in those browsers was causing the tabs not to be displayed. The CORS error happened when fetching data from crossref.
This PR comments out the request to crossref and the crossref tab in the explorer UI. We can bring those back once the CORS issue is fixed.
Other changes in this pr:
- The explorer's page title is now "Docmap Explorer" instead of "Docmap Demonstration"
- Adjust font styling for tooltips
List any issues that are related to this pull request, such as bug reports or feature requests.

Fix Docmap Explorer in Firefox

---

packages/etl/package.json
packages/spa/src/App.svelte
pnpm-lock.yaml

Fixes crossref demo in explorer in Safari and Firefox
Awaiting word from Crossref whether there is a way to be Polite while on Firefox.

fix crossref demo in the Explorer
